title: Open Disclosure San Jose
description: This web app will display campaign finance information about San Jose city office election contributuions. Code for San Jose version of Open Disclosure app originally rolled by Open Oakland. 
theme: jekyll-theme-slate